services:
    epa_redis:
      image: redis
      ports:
        - '6379:6379'
      hostname: epa-redis
      command: /bin/sh -c "redis-server --requirepass ${EPA_REDIS_PASSWORD}"
      environment:
         EPA_REDIS_HOSTNAME: ${EPA_REDIS_HOSTNAME}
         EPA_REDIS_PORT: ${EPA_REDIS_PORT}
         EPA_REDIS_PASSWORD: ${EPA_REDIS_PASSWORD}