# coding: utf-8

"""
    EPA (Event Posting App) API

    API for a mobile safety application that allows users to post and subscribe  to local safety concerns. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from epa_api.apis.authentication_api import router as AuthenticationApiRouter
from epa_api.apis.system_api import router as SystemApiRouter

app = FastAPI(
    title="EPA (Event Posting App) API",
    description="API for a mobile safety application that allows users to post and subscribe  to local safety concerns. ",
    version="1.0.0",
)

app.include_router(AuthenticationApiRouter)
app.include_router(SystemApiRouter)
