# coding: utf-8

"""
    EPA (Event Posting App) API

    API for a mobile safety application that allows users to post and subscribe to local safety concerns. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi.openapi.docs import get_swagger_ui_html
from fastapi import FastAPI, Request
from mangum import Mangum
from pathlib import Path
from typing import Dict, Any
import yaml

from epa_api.apis.authentication_api import router as AuthenticationApiRouter
from epa_api.apis.system_api import router as SystemApiRouter
from epa_api.apis.posts_api import router as PostsApiRouter
from epa_api.apis.category_api import router as CategoryApiRouter
from epa_api.api_implementation.utils.context import current_token_data
from epa_api.models.extra_models import TokenModel
import logging
logging.basicConfig(level=logging.DEBUG)

app = FastAPI(
    title="EPA (Event Posting App) API",
    description="API for a mobile safety application that allows users to post and subscribe to local safety concerns. ",
    version="1.0.0",
)

@app.middleware("http")
async def persist_auth_context(request: Request, call_next):
    
    auth_header = request.headers.get("Authorization")
    
    if auth_header and auth_header.lower().startswith("bearer "):
        try:
            token_str = auth_header.split(" ")[1]
            token_model = TokenModel(sub=token_str)
            current_token_data.set(token_model)
        except Exception:
             # Let the Security dependency handle formal errors
            pass
            
    # Proceed to the Router -> Security Dependency -> Implementation
    response = await call_next(request)
    return response
  
def custom_openapi() -> Dict[str, Any]:
    """Generated OpenAPI schema if does not exist"""
    if app.openapi_schema:
        return app.openapi_schema
    
    current_dir = Path(__file__).parent
    
    yaml_path = current_dir / "openapi.yml"
    
    try:
        with open(yaml_path, "r") as file:
            openapi_schema = yaml.safe_load(file)
            
        app.openapi_schema = openapi_schema
        return app.openapi_schema
        
    except FileNotFoundError:
        from fastapi.openapi.utils import get_openapi
        return get_openapi(title="EPA API (Generated from FastAPI)", version="1.0.0", routes=app.routes)
        
@app.get("/docs", include_in_schema=False)
def custom_swagger_ui_html(request: Request):
    """Custom /docs route for OpenAPI"""
    aws_event = request.scope.get("aws.event", {})
    stage = aws_event.get("requestContext", {}).get("stage", "")
    
    # Construct the explicit path
    prefix = f"/{stage}" if stage else ""
    openapi_url = f"{prefix}/openapi.json"
    
    return get_swagger_ui_html(
        openapi_url=openapi_url,
        title="EPA API (Generated with FastAPI)"
    )
            
app.include_router(AuthenticationApiRouter)
app.include_router(SystemApiRouter)
app.include_router(PostsApiRouter)
app.include_router(CategoryApiRouter)

# Lambda Handler
handler = Mangum(app)

# OpenAPI work in Lambda
app.openapi = custom_openapi