services:
  epa_kafka_broker:
    build:
      context: .
      args:
        EPA_KAFKA_ADMIN_PASSWORD: ${EPA_KAFKA_ADMIN_PASSWORD}
        EPA_KAFKA_PRODUCER_PASSWORD: ${EPA_KAFKA_PRODUCER_PASSWORD}
        EPA_KAFKA_CONSUMER_PASSWORD: ${EPA_KAFKA_CONSUMER_PASSWORD}
    container_name: epa_kafka_broker
    hostname: epa-kafka-broker
    ports:
      - "9094:9094" # If you want to test connection directly to kafka without a containerized app
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,EXTERNAL://epa-kafka-broker:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT # All are plaintext since no security in testing
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SUPER_USERS: User:ANONYMOUS;User:admin # Users that are unauthorizered (which are only on port 9092 & 9093
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_OPTS: -Djava.security.auth.login.config=/opt/kafka/config/jaas.conf
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@epa-kafka-broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
  
