name: "Deploy API and Dependencies"

on:
  push:
    branches:
      - main
  pull_request:
    breaches:
      - main

jobs:
  environment: production
  # Deploy dependencies
  deploy-database:
    uses: NateMartes/epa/.github/workflows/deploy-db.yml@feature/create-api-workflow
    
  deploy-kafka:
    uses: NateMartes/epa/.github/workflows/deploy-kafka.yml@feature/create-api-workflow